name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ['3.8', '3.9', '3.10']

    runs-on: ${{ matrix.os }}-latest

    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install poetry
    - run: poetry install

    - run: make lint
    - run: make mypy

    - run: make test

    - run: poetry run coverage xml

    - uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml
        env_vars: PYTHON,OS

  deploy:
    needs:
      - test
      - lint
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: install
        run: |
          pip install -U pip setuptools wheel twine
          pip install .

      - name: set version
        run: VERSION_PATH='dirty_equals/version.py' python <(curl -Ls https://git.io/JT3rm)

      - run: python setup.py sdist bdist_wheel

      - run: twine check dist/*

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
